grafana:
  admin:
    existingSecret: varnishcluster-grafana-admin-password
  sidecar:
    datasources:
      enabled: true
      labels:
        grafana_datasource: "1"
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"