FROM golang:1.17.6-bullseye AS builder

ENV DEBIAN_FRONTEND=noninteractive INSTALL_DIRECTORY=/usr/local/bin

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends git curl

WORKDIR /go/src/github.com/ibm/varnish-operator

ENV GOPROXY=https://proxy.golang.org

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg
COPY api/ api/

ARG VERSION=undefined

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build \
    -ldflags "-X main.Version=$VERSION" \
    -a \
    -o varnish-controller \
    ./cmd/varnish-controller/


FROM debian:bullseye-slim as binary

RUN apt-get update && apt-get install -y --no-install-recommends varnish


# Build Final Varnish image
FROM debian:bullseye-slim
LABEL maintainer="Alex Lytvynenko <oleksandr.lytvynenko@ibm.com>, Tomash Sidei <tomash.sidei@ibm.com>"

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends libc6 libedit2 libncursesw6 libtinfo6 libvarnishapi2 \
    && rm -rf /var/lib/apt/lists/* \
                    /etc/varnish/* \
    && adduser --quiet --system --no-create-home --home /nonexistent --group varnish \
    && mkdir -p /etc/varnish /var/lib/varnish \
    && chown -R varnish /etc/varnish /var/lib/varnish

COPY --from=binary /usr/bin/varnishadm /usr/bin/varnishstat /usr/bin/
COPY --from=builder /go/src/github.com/ibm/varnish-operator/varnish-controller /varnish-controller

USER varnish

ENTRYPOINT ["/varnish-controller"]
