#!/bin/sh
# Start varnish-controller
echo -n "** Waiting for Varnish to start..."
until varnishadm ping 2> /dev/null; do echo -n .; sleep 0.2; done;
echo "** Starting varnish-controller"
/varnish-controller
