container:
  # path to image + tag
  image: us.icr.io/icm-docker-images/varnish-operator:cin
  imagePullPolicy: Always
  imagePullSecret: "all-icr-io"
logLevel: info
logFormat: json
monitoring:
  grafanaDashboard:
    enabled: true
    datasourceName: "Prometheus"
  prometheusServiceMonitor:
    enabled: true
