{
 "title": "Varnish Operator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of reconciliations per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total[1m])) by (result)",
     "legendFormat": "result={{result}}"
    }
   ]
  },
  {
   "title": "Reconciliation time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "REST client requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total[1m])) by (code, method)",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "REST client latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rest_client_request_latency_seconds_sum[1m])) by (url, verb)",
     "legendFormat": "{{url}} {{verb}}"
    }
   ]
  },
  {
   "title": "Work Queue depth",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(workqueue_depth)" }
   ]
  },
  {
   "title": "Work Queue retries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(workqueue_retries_total[1m]))",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{pod}} ({{instance}})" }
   ]
  },
  {
   "title": "Webhook latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_count[1m])) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webook requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total[1m])) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Reconcile errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total[1m]))",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}