{{- $replicas := .Values.replicas | toString | float64 }}
{{ if gt $replicas 1.0 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: varnish-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: varnish-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: varnish-operator
    namespace: {{ .Release.Namespace }}
{{ end }}