apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: '1.0'
  name: varnishservices.icm.ibm.com
spec:
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
    shortNames:
    - vs
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.deployment.replicas
      statusReplicasPath: .status.deployment.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployment:
              properties:
                affinity:
                  type: object
                imagePullPolicy:
                  type: string
                imagePullSecretName:
                  type: string
                livenessProbe:
                  type: object
                readinessProbe:
                  type: object
                replicas:
                  format: int32
                  type: integer
                tolerations:
                  items:
                    type: object
                  type: array
                varnishMemory:
                  type: string
                varnishResources:
                  type: object
                varnishRestartPolicy:
                  type: string
                vclFileConfigMapName:
                  pattern: '[a-z0-9\\-.]+'
                  type: string
              required:
              - imagePullSecretName
              type: object
            service:
              properties:
                ports:
                  maxItems: 1
                  type: array
              type: object
            vclConfigMap:
              properties:
                backendsFile:
                  type: string
                defaultFile:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
          required:
          - vclConfigMap
          - deployment
          - service
          type: object
        status:
          properties:
            deployment:
              type: object
            service:
              properties:
                cached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
                noCached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
