apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: '1.0'
  name: varnishservices.icm.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.statefulSet.replicas
    description: desired number of varnish pods
    format: int32
    name: Desired
    type: integer
  - JSONPath: .status.statefulSet.readyReplicas
    description: current number of varnish pods
    format: int32
    name: Current
    type: integer
  - JSONPath: .status.statefulSet.updatedReplicas
    description: number of varnish pods that are up to date
    format: int32
    name: Up-To-Date
    type: integer
  - JSONPath: .status.vcl.configMapVersion
    description: version of the ConfigMap containing the VCL
    name: VCL-Version
    type: string
  - JSONPath: .status.service.ip
    description: IP Address of the service backed by Varnish
    name: Service-IP
    type: string
  - JSONPath: .status.serviceNoCache.ip
    description: IP Address of the service without any caching
    name: ServiceNoCache-IP
    type: string
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
    shortNames:
    - vs
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.statefulSet.replicas
      statusReplicasPath: .status.statefulSet.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          properties:
            name:
              maxLength: 40
              type: string
          type: object
        spec:
          properties:
            logFormat:
              enum:
              - json
              - console
              type: string
            logLevel:
              enum:
              - debug
              - info
              - warn
              - error
              - dpanic
              - panic
              - fatal
              type: string
            podDisruptionBudget:
              type: object
            service:
              properties:
                prometheusAnnotations:
                  type: boolean
                varnishExporterPort:
                  properties:
                    name:
                      maxLength: 15
                      type: string
                  type: object
                varnishPort:
                  properties:
                    name:
                      maxLength: 15
                      type: string
                  type: object
              required:
              - varnishPort
              type: object
            statefulSet:
              properties:
                affinity:
                  type: object
                container:
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    imagePullSecret:
                      type: string
                    livenessProbe:
                      properties:
                        exec:
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                    readinessProbe:
                      properties:
                        exec:
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                    resources:
                      type: object
                    restartPolicy:
                      type: string
                    varnishArgs:
                      items:
                        type: string
                      type: array
                  type: object
                replicas:
                  format: int32
                  type: integer
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            vclConfigMap:
              properties:
                entrypointFile:
                  pattern: ^.+\.vcl$
                  type: string
                name:
                  type: string
              required:
              - name
              - entrypointFile
              type: object
          required:
          - vclConfigMap
          - service
          type: object
        status:
          properties:
            service:
              properties:
                ip:
                  type: string
                loadBalancer:
                  description: LoadBalancer contains the current status of the load-balancer,
                    if one is present.
                  type: object
                name:
                  type: string
              type: object
            serviceNoCache:
              properties:
                ip:
                  type: string
                loadBalancer:
                  description: LoadBalancer contains the current status of the load-balancer,
                    if one is present.
                  type: object
                name:
                  type: string
              type: object
            statefulSet:
              properties:
                name:
                  type: string
                varnishArgs:
                  type: string
              type: object
            vcl:
              properties:
                availability:
                  type: string
                configMapVersion:
                  type: string
                version:
                  type: string
              required:
              - configMapVersion
              - availability
              type: object
          required:
          - vcl
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
