apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: varnish-operator
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: varnish-service-controller-manager-service
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
        admission-controller: "varnish-service-admission-controller"
    spec:
      serviceAccountName: varnish-operator
      containers:
      - name: varnish-operator
        image: {{ .Values.container.image | quote }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy | title | quote }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: LEADERELECTION_ENABLED
          value: {{ if gt .Values.replicas 1.0 }}"true"{{ else }}"false"{{ end }}
        - name: CONTAINER_IMAGE
          value: {{ .Values.container.image | quote }}
        - name: LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name: LOGFORMAT
          value: {{ .Values.logFormat | quote }}
        - name: CONTAINER_METRICSPORT
          value: {{ .Values.container.metricsPort | quote }}
        - name: CONTAINER_WEBHOOKPORT
          value: {{ .Values.container.webhookPort | quote }}
        resources: {{ toYaml .Values.container.resources | nindent 10 }}
        ports:
          - containerPort: {{ .Values.container.metricsPort }}
            name: metrics
          - containerPort: {{ .Values.container.webhookPort }}
            name: webhook
      restartPolicy: {{ .Values.container.restartPolicy | quote }}
      {{- with .Values.container.imagePullSecret }}
      imagePullSecrets:
      - name: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
