{
 "title": "Varnish",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "varnish_instance", "label": "Instance" }
  ]
 },
 "panels": [
  { "title": "Real time metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Cache Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(\n  (\n    rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]) / (rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]) + rate(varnish_main_cache_miss{instance=~\"^($varnish_instance).*\"}[1m]))\n  )\n)"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m])) + sum(irate(varnish_main_cache_miss{instance=~\"^($varnish_instance).*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions_total{instance=~\"^($varnish_instance).*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(varnish_main_vmods{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(varnish_main_uptime{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "varnish_version{instance=~\"^($varnish_instance).*\"}"
    }
   ]
  },
  { "title": "Varnish requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Varnish Overall Req/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{}[1m])) + sum(irate(varnish_main_cache_miss{}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Reqs/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{}[1m]))",
     "legendFormat": "cache hits"
    },
    {
     "expr": "sum(irate(varnish_main_cache_miss{}[1m]))",
     "legendFormat": "cache misses"
    }
   ]
  },
  {
   "title": "Queued Requests/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_thread_queue_len{}[1m]))",
     "legendFormat": "queued requests"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]) / (rate(varnish_main_cache_miss{instance=~\"^($varnish_instance).*\"}[1m])+rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m])))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]) / (rate(varnish_main_cache_miss{instance=~\"^($varnish_instance).*\"}[1m])+rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[1m]))))",
     "legendFormat": "cache miss %"
    }
   ]
  },
  {
   "title": "Cache Pass Reqs/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ]
  },
  {
   "title": "Dropped Requests/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_req_dropped{}[1m]))",
     "legendFormat": "dropped"
    }
   ]
  },
  { "title": "Varnish memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "varnish_sma_g_bytes{type=\"s0\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "LRU moved"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "LRU nuked"
    },
    {
     "expr": "sum(varnish_sma_g_bytes{type=\"s0\", instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "mem used"
    }
   ]
  },
  {
   "title": "Expired Objects/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{}[1m]))",
     "legendFormat": "expired objects"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{instance=~\"^($varnish_instance).*\"}[1m]) + irate(varnish_main_s_resp_bodybytes{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[1m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[1m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[1m])) by (backend)",
     "legendFormat": "backend {{ backend }}"
    }
   ]
  },
  {
   "title": "Nuked Objects/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{}[1m]))",
     "legendFormat": "nuked"
    }
   ]
  },
  { "title": "Varnish internals metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Requests sent to sleep sleep per seconds",
   "type": "graph",
   "description": "Number of requests sent to sleep without a worker thread because\n        they found a busy object.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_busy_sleep[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Backend retries per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_backend_retry[1m]))",
     "legendFormat": "retries "
    }
   ]
  },
  {
   "title": "Threads limited per second",
   "type": "graph",
   "description": "Number of times more threads were needed, but limit was reached in\n        a thread pool. See also parameter thread_pool_max.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_threads_limited[1m]))",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Number of sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Length of session queue",
   "type": "graph",
   "description": "Number of times session was queued waiting for a thread. See also\n        parameter thread_queue_limit.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(varnish_main_thread_queue_len)",
     "legendFormat": "queue"
    }
   ]
  },
  {
   "title": "Number of fetches per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_fetch{}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}