#!/bin/sh

# Generate a unique timestamp ID for this version of the VCL
TIME=$(date +%s)

# Load the file into memory
varnishadm -S "$VCL_DIR/secret" -T 127.0.0.1:6082 vcl.load "varnish_$TIME" "$VCL_DIR/$DEFAULT_FILE"

# Active this Varnish config
varnishadm -S "$VCL_DIR/secret" -T 127.0.0.1:6082 vcl.use varnish_$TIME
