/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	icm_v1alpha1 "icm-varnish-k8s-operator/operator/controller/pkg/apis/icm/v1alpha1"
	versioned "icm-varnish-k8s-operator/operator/controller/pkg/client/clientset/versioned"
	internalinterfaces "icm-varnish-k8s-operator/operator/controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "icm-varnish-k8s-operator/operator/controller/pkg/client/listers/icm/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VarnishServiceInformer provides access to a shared informer and lister for
// VarnishServices.
type VarnishServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VarnishServiceLister
}

type varnishServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVarnishServiceInformer constructs a new informer for VarnishService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVarnishServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVarnishServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVarnishServiceInformer constructs a new informer for VarnishService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVarnishServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IcmV1alpha1().VarnishServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IcmV1alpha1().VarnishServices(namespace).Watch(options)
			},
		},
		&icm_v1alpha1.VarnishService{},
		resyncPeriod,
		indexers,
	)
}

func (f *varnishServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVarnishServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *varnishServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&icm_v1alpha1.VarnishService{}, f.defaultInformer)
}

func (f *varnishServiceInformer) Lister() v1alpha1.VarnishServiceLister {
	return v1alpha1.NewVarnishServiceLister(f.Informer().GetIndexer())
}
