apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-prometheus-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  {{ .Release.Name }}-datasource.yaml: |-
    apiVersion: 1

    datasources:
    - name: Prometheus-varnish
      type: prometheus
      access: proxy
      orgId: 1
      url: http://{{ .Release.Name }}-prometheus:9090
      version: 1
      editable: false
