apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    tier: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      app: varnish
  serviceAccountName: {{ .Release.Name }}-prometheus
  resources:
    requests:
      memory: 400Mi
